from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = (
    ROOT
    / "docs"
    / "experiment_records"
    / "compact_metrics"
    / "2026-07-18_qwen3_1p7b_math_ood_corrected_master_table.json"
)
OUTPUT = ROOT / "docs" / "technical_report" / "generated" / "corrected_master_table.tex"
MANIFEST = OUTPUT.with_suffix(".manifest.json")

COLUMNS = (
    ("math500", r"MATH-500"),
    ("gsm8k", r"GSM8K"),
    ("olympiad", r"\shortstack{Olympiad\\Bench}"),
    ("amc_avg32", r"\shortstack{AMC\\Avg@32}"),
    ("math_avg", r"MathAvg$^\dagger$"),
    ("amc_greedy", r"\shortstack{AMC\\greedy}"),
    ("humaneval_plus", r"\shortstack{HumanEval+\\corrected}"),
    ("mbpp", r"MBPP$^*$"),
    ("livecodebench", r"\shortstack{LiveCodeBench\\corrected}"),
    ("code_avg", r"CodeAvg$^{*\dagger}$"),
    ("gpqa_diamond", r"\shortstack{GPQA-\\Diamond}"),
    ("mmlu_pro", r"MMLU-Pro"),
    ("reasoning_avg", r"ReasAvg$^\dagger$"),
    ("gpqa_freeform", r"\shortstack{GPQA-Diamond-\\Freeform}"),
    ("ceval", r"C-Eval"),
    ("ifeval", r"IFEval"),
    ("mgsm", r"MGSM"),
    ("language_avg", r"LangAvg$^\dagger$"),
)

HARD_COLUMNS = {"olympiad", "livecodebench", "gpqa_freeform"}
AVERAGE_COLUMNS = {"math_avg", "code_avg", "reasoning_avg", "language_avg"}


def row_label(row: dict) -> str:
    prefix = "TriGLU" if row["setting"].startswith("TriGLU") else "Baseline"
    if row["row_type"] == "summary":
        return rf"\textbf{{{prefix} mean $\pm$ std}}"
    return f"{prefix}-{row['step']}"


def metric_value(row: dict, metric: str) -> str:
    value = row["metrics"][metric]
    if value is None:
        return "--"
    if row["row_type"] == "summary":
        std = row["population_std"][metric]
        return rf"${value:.2f}\pm{std:.2f}$"
    return f"{value:.3f}"


def styled(value: str, metric: str) -> str:
    if metric in HARD_COLUMNS:
        if value.startswith("$") and value.endswith("$"):
            return rf"$\mathbf{{{value[1:-1]}}}$"
        return rf"\textbf{{{value}}}"
    if metric in AVERAGE_COLUMNS:
        return rf"\textcolor{{gray}}{{{value}}}"
    return value


def header(label: str, metric: str) -> str:
    if metric in HARD_COLUMNS:
        return rf"\textbf{{{label}}}"
    if metric in AVERAGE_COLUMNS:
        return rf"\textcolor{{gray}}{{{label}}}"
    return label


def main() -> None:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    rows = payload["rows"]
    assert len(rows) == 12
    assert all(row["stage"].startswith("GRPO") for row in rows)

    lines = [
        "% Generated by scripts/render_qwen3_1p7b_math_ood_report_table_tex.py.",
        f"% Source SHA-256: {hashlib.sha256(SOURCE.read_bytes()).hexdigest()}",
        r"\begingroup",
        r"\setlength{\tabcolsep}{2.2pt}",
        r"\renewcommand{\arraystretch}{1.12}",
        r"\scriptsize",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{l*{18}{r}}",
        r"\toprule",
        r"Setting & \multicolumn{6}{c}{Math} & \multicolumn{4}{c}{Code} & \multicolumn{4}{c}{Reasoning} & \multicolumn{4}{c}{Language} \\",
        r"\cmidrule(lr){2-7}\cmidrule(lr){8-11}\cmidrule(lr){12-15}\cmidrule(lr){16-19}",
        "Setting & " + " & ".join(header(label, metric) for metric, label in COLUMNS) + r" \\",
        r"\midrule",
    ]

    for index, row in enumerate(rows):
        if index == 6:
            lines.append(r"\midrule")
        values = [styled(metric_value(row, metric), metric) for metric, _ in COLUMNS]
        lines.append(row_label(row) + " & " + " & ".join(values) + r" \\")
        if row["row_type"] == "summary" and index != len(rows) - 1:
            lines.append(r"\addlinespace[2pt]")

    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}%",
            r"}",
            r"\par\vspace{4pt}",
            r"\begin{minipage}{\linewidth}\footnotesize",
            r"\textbf{Evidence hierarchy.} Bold columns are the three hard generative benchmarks: OlympiadBench, corrected LiveCodeBench, and GPQA-Diamond-Freeform. All Avg columns are muted because they are naive equal-weight descriptive summaries, not model-selection objectives.\\",
            r"\textbf{GPQA-Freeform accounting.} Each checkpoint is scored over 126 manually audited questions. The displayed architecture mean is equivalent to 40/630 correct checkpoint--question runs for TriGLU and 29/630 for baseline; the separate distinct-question union is 18/126 versus 12/126 and is not the table score.\\",
            r"\textbf{Protocol boundary.} HumanEval+ and LiveCodeBench use corrected routes. MBPP and therefore CodeAvg remain provisional. Cap-hit-inclusive results are retained for matched comparison.",
            r"\end{minipage}",
            r"\endgroup",
            "",
        ]
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    manifest = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": str(SOURCE.relative_to(ROOT)),
        "source_sha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        "output": str(OUTPUT.relative_to(ROOT)),
        "output_sha256": hashlib.sha256(OUTPUT.read_bytes()).hexdigest(),
        "row_count": len(rows),
        "display_steps": [158, 196, 226, 256, 294],
        "bold_hard_benchmarks": sorted(HARD_COLUMNS),
        "muted_average_columns": sorted(AVERAGE_COLUMNS),
        "historical_master_table_modified": False,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(OUTPUT)


if __name__ == "__main__":
    main()
